benchmarks = '../benchmarks/**/*.bril'
extract = 'total_dyn_inst: (\d+)'
timeout=60

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.dead_store_elimination]
pipeline = [
    "bril2json",
    "python3 dead_store_elimination.py",
    "brili -p {args}",
]