benchmarks = '../examples/test/lvn/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.lvn]
pipeline = [
  "bril2json | python3 lvn.py | python3 trivial_dce.py",
  "brili -p {args}",
]
