benchmarks = '../benchmarks/**/*.bril'
extract = 'total_dyn_inst: (\d+)'
timeout=60

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.licm]
pipeline = [
    "bril2json",
    "python3 licm.py",
    "brili -p {args}",
]